services:
  db:
    image: postgres:17.2
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    # To bind the example db stored in the host machine to the container
      - ./dvdrental.tar:/dvdrental.tar

    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
